### ISSUE TITLE
오타

### ISSUE THREAD

**Issue by ultramar2ne** [MeongJJeong/Coala_exampleForGit#5]
https://github.com/MeongJJeong/COA_VA_SampleCode/blob/462088745dff43044b6e1a0c0a499f052737d174/PyGame/BankSystem/BankSystemVer02_JH.py#L53

**Comment by ultramar2ne** [comment]
어떻게 생각해? 새로운 이슈?

**Comment by SnovvyOwl** [comment]
이거 조금전에 준희가 수정했어요!
